---
name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SECRET_TOKEN}}"
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: ./script_pipeline.sh
  pop:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/mobsit/test-access.git target
          #rm everything but the .git directory
          ls -l 
          pwd
          cd target
          ls -la
          ./script_pipeline.sh 
          ls -la
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: doc
  ret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SECRET_TOKEN}}"
      - run: >
          
          #  git clone https://github.com/jambonrose/python-web-dev-21-2.git target

          #  #rm everything but the .git directory
           ls -l 
          #  pwd

          #  cd target

          #  ls -la

          #  pwd
           cp doc /home/runner/work/backup/backup/data
          #  cd ..
           ls -la
           git status
           git config --global user.name "mobsit"
           git config --global user.email "khadijamobsit@gmail.com"
          #  cd ..
           git add doc
           git commit -m "Automatic"
           git status
           git push
