---
name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SECRET_TOKEN}}"
      - run: ls -l
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: script_pipeline.sh
  pop:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
         name: code-coverage
        
      - run: |
          git clone https://github.com/mobsit/test-access.git 
          #rm everything but the .git directory
          ls -l 
          pwd
          mv script_pipeline.sh test-access/script_pipeline.sh
          cd test-access
          chmod 777 script_pipeline.sh
          ls -la
          ./script_pipeline.sh 
          ls -la
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: test-access/data
        
  ret:
    needs: pop
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
         name: code-coverage-report
       
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SECRET_TOKEN}}"
      - run: |
      
        
           cd /home/runner/work/backup/backup
          
           ls -l
           cd data
           ls -l
           git status
           git config --global user.name "mobsit"
           git config --global user.email "khadijamobsit@gmail.com"
          
           git add .
           git commit -m "Automatic"
           git status
           git push
