name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - run: echo $GITHUB_SHA
    - name: Build the Docker image
      run: git log  --pretty=oneline   --reverse | sed 's/\|/ /'|awk '{print $1}'
    - name: test
      run: git log  --pretty=oneline   --reverse | sed 's/\|/ /'|awk '{print $1}' | awk -v string="$GITHUB_SHA" -f tst.awk
    - run: ./script_pipeline.sh $GITHUB_SHA
